### ISSUE TITLE
Hover effect for button and transition , transform effect for better UI Experience

### ISSUE THREAD

**Issue by Hari-Kumar-A** [gdscsmit/gdscsmit.github.io#67] opened 2023-10-16 20:32 UTC
<img width="729" alt="image" src="https://github.com/gdscsmit/gdscsmit.github.io/assets/125040587/6c86838f-f040-4b90-893c-8e3497499f24">

I want to add hover effect and transition for better UI experience.  Kindly assign me this under hacktoberfest 2023

**Comment by pooranjoyb** [comment] 2023-10-17 04:29
Hey @Hari-Kumar-A 
Glad to see your contributions but please work on an issue after you get assigned to it. 😄 
Don't directly create PRs after creating the issues. 
The reason is that, if the issue is labelled as `wontfix` , `invalid` or `duplicate` then all your work could go in vain. :/

**Comment by Hari-Kumar-A** [comment] 2023-10-17 08:39
ok , I have updated and give PR. Please check. Thanks

**Closed** 2023-10-17 13:17 UTC
Labels: good first issue, hacktoberfest
